import type { Album } from "./types";

/**
 * A few records on the shelf while the database is still empty.
 * Real artwork is loaded from the Cover Art Archive by MBID.
 */
export const MOCK_ALBUMS: Album[] = [
  {
    id: "mock-kind-of-blue",
    title: "Kind of Blue",
    artist: "Miles Davis",
    year: 1959,
    genres: ["jazz"],
    subgenres: ["modal jazz"],
    coverUrl: "https://coverartarchive.org/release/0497d717-5a73-4be8-bb9a-7c5cb5e44c0e/front-500",
    spineColor: "#2f4f6b",
    featured: true,
    spotifyId: "spotify:album:1weenld61qoidwYuZ1GESA",
    mbid: "0497d717-5a73-4be8-bb9a-7c5cb5e44c0e",
    rating: 5,
    notes:
      "The room's house record. Put it on when the lights are low and nobody needs to talk.",
    mood: ["late night", "focus", "background"],
    playCount: 12,
    lastPlayedAt: "2026-06-20T23:14:00.000Z",
    addedAt: "2026-01-04T18:00:00.000Z",
  },
  {
    id: "mock-a-love-supreme",
    title: "A Love Supreme",
    artist: "John Coltrane",
    year: 1965,
    genres: ["jazz"],
    subgenres: ["spiritual jazz"],
    coverUrl: "https://coverartarchive.org/release/b9b2c2a0-7b8b-3b6b-9b9b-1b1b1b1b1b1b/front-500",
    spineColor: "#8a2c1e",
    featured: false,
    spotifyId: "spotify:album:2GILN6jOZjOGZupGfRYXEr",
    mbid: null,
    rating: 5,
    notes: "Side one, all the way through, no interruptions.",
    mood: ["late night", "melancholy", "loud"],
    playCount: 7,
    lastPlayedAt: "2026-06-11T01:02:00.000Z",
    addedAt: "2026-02-18T20:30:00.000Z",
  },
  {
    id: "mock-the-koln-concert",
    title: "The Köln Concert",
    artist: "Keith Jarrett",
    year: 1975,
    genres: ["jazz"],
    subgenres: ["solo piano"],
    coverUrl: null,
    spineColor: "#b08436",
    featured: false,
    spotifyId: "spotify:album:25Htk3Hfm3qK7Xd9rziT4i",
    mbid: null,
    rating: 4,
    notes: "Rainy afternoons. The squeaky pedal is part of it.",
    mood: ["rainy", "focus", "melancholy"],
    playCount: 4,
    lastPlayedAt: null,
    addedAt: "2026-03-30T15:45:00.000Z",
  },
  {
    id: "mock-mingus-ah-um",
    title: "Mingus Ah Um",
    artist: "Charles Mingus",
    year: 1959,
    genres: ["jazz"],
    subgenres: ["hard bop"],
    coverUrl: null,
    spineColor: "#5a6e3a",
    featured: false,
    spotifyId: "spotify:album:3UAFkX9Cd3wt3If6jj2x2K",
    mbid: null,
    rating: 4,
    notes: "When the room needs a little more pulse.",
    mood: ["upbeat", "energetic", "loud"],
    playCount: 2,
    lastPlayedAt: null,
    addedAt: "2026-05-02T19:10:00.000Z",
  },
];
